### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jenspeterhess** [alengwenus/hass-addons#2]
Unfortunately, I get the following error message during installation.

<img width="482" alt="Bildschirmfoto 2024-08-27 um 08 28 37" src="https://github.com/user-attachments/assets/e04227c6-bdb4-40d6-a566-9d4fa6ed21bb">

Am I missing any authorizations during the installation or do I need to install other add-ons?

**Comment by alengwenus** [comment]
I pinned the WiringPi version to v3.2 which solves the problem for me.
Could you retry, please?

**Comment by jenspeterhess** [comment]
Yes, I have tried it again.Unfortunately without success…..    Von: Andre Lengwenus ***@***.***>Datum: Dienstag, 27. August 2024 um 13:48An: alengwenus/hass-addons ***@***.***>Cc: jenspeterhess ***@***.***>, Author ***@***.***>Betreff: Re: [alengwenus/hass-addons] Installation error (Issue #2)I pinned the WiringPi version to v3.2 which solves the problem for me.Could you retry, please?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by jenspeterhess** [comment]
Yes, I have tried it again.
Unfortunately without success….
<img width="485" alt="Bildschirmfoto 2024-08-27 um 14 12 45" src="https://github.com/user-attachments/assets/171c7cd0-d955-4f5e-ad96-ce5b90d719cd">
<img width="945" alt="Bildschirmfoto 2024-08-27 um 14 11 03" src="https://github.com/user-attachments/assets/c00e9818-dfa3-4bf9-991a-b095061c02a0">

**Comment by alengwenus** [comment]
Can you confirm that you have completely uninstalled the add-on and refreshed the repository before installing the add-on again? Version shown should be 1.0.3.

**Comment by jenspeterhess** [comment]
Oh.... yes
Now I got the new version (1.03) - Great!
but unfortunately I am running into a new error.

I have only updated the password in the configuration. All other information is in the standard.
What information is specific to my LCN installation?
Is it perhaps due to the DIM mode steps? My installation is old and needs the 50. Where can I enter this information?

<img width="843" alt="Bildschirmfoto 2024-08-27 um 16 15 17" src="https://github.com/user-attachments/assets/d2df7c3e-469b-4107-b9d4-f3c92c4ec914">


<img width="814" alt="Bildschirmfoto 2024-08-27 um 16 15 34" src="https://github.com/user-attachments/assets/5da4bbe3-1508-471c-a190-793cc802b1ab">

<img width="591" alt="Bildschirmfoto 2024-08-27 um 16 14 30" src="https://github.com/user-attachments/assets/ff012510-4ff7-477c-b422-1f02bc2f29af">

**Comment by alengwenus** [comment]
I guess this has something to do with the newer WiringPi versions. I guess you are running HASS on a RaspberryPi. Unfortunately I currently cannot test on that platform.
I can just try to move back in versions until we found one which works.
I moved back to version 2.61-1. Could you please try to install the add-on again?

**Comment by jenspeterhess** [comment]
no, unfortunately it doesn't work either

<img width="432" alt="Bildschirmfoto 2024-08-27 um 17 40 43" src="https://github.com/user-attachments/assets/29e2b92d-3269-4942-946e-2cc4b4efd4ac">

**Comment by alengwenus** [comment]
I'm afraid, but I don't think I'll be able to help in the short term.  Do you have other possibilities to connect to the LCN bus (like a LCN VISU?).

**Comment by alengwenus** [comment]
Or we could tryout all available WiringPi versions hoping that one of them would do...

**Comment by alengwenus** [comment]
I just got another idea, what we could try out. I'll try to implement that this evening. I'll let you know.

**Comment by jenspeterhess** [comment]
Great!!!!
The manual LCN integration also comes from you, doesn't it? That worked for me straight away.
That would be an alternative for me.

What exactly is the advantage of this integration? More convenience and overview when installing the LCN modules?

**Comment by alengwenus** [comment]
Ok, next try... 😄  Could you please re-install the add-on?

And to answer your question:  The HA LCN integration ([here](https://www.home-assistant.io/integrations/lcn/)) connects to a PCK host. This can be either the PCHK software (in combination with a connected LCN-PK or PKU) or a LCN-PKE or LCN-VISU. The integration is needed in any case.
This add-on just wraps the PCHK software, so it can be run within HomeAssistant as an add-on.
You could also install a LCN-VISU and configure the LCN integration to connect to it. Then you wouldn't need this add-on. I definetely would recommend to do it that way even if it costs you some money.

**Comment by jenspeterhess** [comment]
I have reinstalled and it seems to be working. Very good.
How can I find my LCN modules now? Are they recognized automatically?

**Comment by alengwenus** [comment]
You have to setup the integration as described here: https://www.home-assistant.io/integrations/lcn/

For this you need to know the IDs and configurations of all your modules (e.g. from LCN-Pro). There is no automatic detection as this is not possible with the PCK interface.

Btw.: Starting with Home Assistant 2024.9.0, which will be released next week, setting up the LCN integration will be possible by using only the UI (integrations menu).
